import yt_dlp
from yt_dlp.utils import DownloadCancelled

def _format_duration(seconds):
    seconds = int(seconds or 0)
    m, s = divmod(seconds, 60)
    h, m = divmod(m, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"

def fetch_video_info(url):
    ydl_opts = {'quiet': True, 'no_warnings': True}
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)
        return {
            "title": info.get("title", "Unknown Video"),
            "thumbnailUrl": info.get("thumbnail", ""),
            "durationText": _format_duration(info.get("duration", 0)),
            "formats": [
                {"id": "full", "label": "Video + Audio (Best Quality)",
                 "subtitle": "Best available · MP4",
                 "sizeText": "Size depends on the best quality available"},
                {"id": "audio", "label": "Audio Only",
                 "subtitle": "M4A", "sizeText": "5-10 MB"},
                {"id": "fast", "label": "Fast Download",
                 "subtitle": "720p · MP4", "sizeText": "<50 MB"},
            ]
        }

def fetch_video(url, ffmpeg_dir, output_dir, format_type, callback):
    def progress_hook(d):
        if callback.isCancelled():
            raise DownloadCancelled("User cancelled")
        if d['status'] == 'downloading':
            total = d.get('total_bytes') or d.get('total_bytes_estimate') or 0
            downloaded = d.get('downloaded_bytes', 0)
            percent = int((downloaded / total) * 100) if total else 0
            callback.onProgress(percent, "downloading")
        elif d['status'] == 'finished':
            callback.onProgress(100, "processing")

    base = {
        'progress_hooks': [progress_hook],
        'ffmpeg_location': ffmpeg_dir,
        'outtmpl': f'{output_dir}/%(title)s_{format_type}.%(ext)s',
        'overwrites': True,
        'nopart': False,
        'socket_timeout': 30,
        'retries': 10,
        'fragment_retries': 10,
        'extractor_retries': 3,
    }

    if format_type == "full":
        opts = {**base, 'format': 'bestvideo+bestaudio/best', 'merge_output_format': 'mp4'}
    elif format_type == "audio":
        opts = {**base, 'format': 'bestaudio[ext=m4a]/bestaudio'}
    else:
        opts = {**base, 'format': 'best[height<=720][ext=mp4]/best[height<=720]'}

    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=True)
        return ydl.prepare_filename(info)


# ---------------------------------------------------------------------------
# Playlist support (Feature 2)
#
# Kept deliberately shallow: extract_flat gives us titles/ids/durations in a
# single request instead of one deep extraction per video, which keeps the
# checklist screen fast even for 100+ item playlists.
# ---------------------------------------------------------------------------

def is_playlist(url):
    """True when the URL points at a playlist rather than a single video."""
    try:
        from urllib.parse import urlparse, parse_qs
        parsed = urlparse(url)
        query = parse_qs(parsed.query)
        list_id = (query.get("list") or [""])[0]
        if list_id and not list_id.startswith("RD"):  # RD* = autogenerated radio mix
            return True
        return "/playlist" in parsed.path
    except Exception:
        return False


def fetch_playlist_info(url):
    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'extract_flat': 'in_playlist',
        'skip_download': True,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)

    entries = []
    for entry in (info.get("entries") or []):
        if not entry:
            continue
        video_id = entry.get("id") or ""
        entry_url = entry.get("url") or entry.get("webpage_url") or ""
        if entry_url and not entry_url.startswith("http"):
            entry_url = "https://www.youtube.com/watch?v=" + entry_url
        if not entry_url and video_id:
            entry_url = "https://www.youtube.com/watch?v=" + video_id

        thumb = ""
        thumbs = entry.get("thumbnails") or []
        if thumbs:
            thumb = thumbs[-1].get("url", "")
        if not thumb and video_id:
            thumb = "https://i.ytimg.com/vi/%s/hqdefault.jpg" % video_id

        entries.append({
            "id": video_id or entry_url,
            "url": entry_url,
            "title": entry.get("title") or "Untitled",
            "thumbnailUrl": thumb,
            "durationText": _format_duration(entry.get("duration", 0)),
        })

    return {
        "title": info.get("title", "Playlist"),
        "entries": entries,
    }
