import yt_dlp
from yt_dlp.utils import DownloadCancelled

def _format_duration(seconds):
    seconds = int(seconds or 0)
    m, s = divmod(seconds, 60)
    h, m = divmod(m, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"

def fetch_video_info(url):
    ydl_opts = {'quiet': True, 'no_warnings': True}
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)
        return {
            "title": info.get("title", "Unknown Video"),
            "thumbnailUrl": info.get("thumbnail", ""),
            "durationText": _format_duration(info.get("duration", 0)),
            "formats": [
                {"id": "full", "label": "Video + Audio (Best Quality)",
                 "subtitle": "Best available · MP4",
                 "sizeText": "Size depends on the best quality available"},
                {"id": "audio", "label": "Audio Only",
                 "subtitle": "M4A", "sizeText": "5-10 MB"},
                {"id": "fast", "label": "Fast Download",
                 "subtitle": "720p · MP4", "sizeText": "<50 MB"},
            ]
        }

def fetch_video(url, ffmpeg_dir, output_dir, format_type, callback):
    def progress_hook(d):
        if callback.isCancelled():
            raise DownloadCancelled("User cancelled")
        if d['status'] == 'downloading':
            total = d.get('total_bytes') or d.get('total_bytes_estimate') or 0
            downloaded = d.get('downloaded_bytes', 0)
            percent = int((downloaded / total) * 100) if total else 0
            callback.onProgress(percent, "downloading")
        elif d['status'] == 'finished':
            callback.onProgress(100, "processing")

    base = {
        'progress_hooks': [progress_hook],
        'ffmpeg_location': ffmpeg_dir,
        'outtmpl': f'{output_dir}/%(title)s_{format_type}.%(ext)s',
        'overwrites': True,
        'nopart': False,
        'socket_timeout': 30,
        'retries': 10,
        'fragment_retries': 10,
        'extractor_retries': 3,
    }

    if format_type == "full":
        opts = {**base, 'format': 'bestvideo+bestaudio/best', 'merge_output_format': 'mp4'}
    elif format_type == "audio":
        opts = {**base, 'format': 'bestaudio[ext=m4a]/bestaudio'}
    else:
        opts = {**base, 'format': 'best[height<=720][ext=mp4]/best[height<=720]'}

    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=True)
        return ydl.prepare_filename(info)


# ---------------------------------------------------------------------------
# Playlist support (Feature 2)
#
# Kept deliberately shallow: extract_flat gives us titles/ids/durations in a
# single request instead of one deep extraction per video, which keeps the
# checklist screen fast even for 100+ item playlists.
# ---------------------------------------------------------------------------

def is_playlist(url):
    """True when the URL points at a playlist rather than a single video."""
    try:
        from urllib.parse import urlparse, parse_qs
        parsed = urlparse(url)
        query = parse_qs(parsed.query)
        list_id = (query.get("list") or [""])[0]
        if list_id and not list_id.startswith("RD"):  # RD* = autogenerated radio mix
            return True
        return "/playlist" in parsed.path
    except Exception:
        return False


def fetch_playlist_info(url):
    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'extract_flat': 'in_playlist',
        'skip_download': True,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)

    entries = []
    for entry in (info.get("entries") or []):
        if not entry:
            continue
        video_id = entry.get("id") or ""
        entry_url = entry.get("url") or entry.get("webpage_url") or ""
        if entry_url and not entry_url.startswith("http"):
            entry_url = "https://www.youtube.com/watch?v=" + entry_url
        if not entry_url and video_id:
            entry_url = "https://www.youtube.com/watch?v=" + video_id

        thumb = ""
        thumbs = entry.get("thumbnails") or []
        if thumbs:
            thumb = thumbs[-1].get("url", "")
        if not thumb and video_id:
            thumb = "https://i.ytimg.com/vi/%s/hqdefault.jpg" % video_id

        entries.append({
            "id": video_id or entry_url,
            "url": entry_url,
            "title": entry.get("title") or "Untitled",
            "thumbnailUrl": thumb,
            "durationText": _format_duration(entry.get("duration", 0)),
        })

    return {
        "title": info.get("title", "Playlist"),
        "entries": entries,
    }


# ---------------------------------------------------------------------------
# Spotify support (Features 3 & 4)
#
# Deliberately credential-free: we only touch Spotify's *public* oEmbed
# endpoint and the public track page HTML. No Web API, no client id/secret,
# no login. Playlists/albums are never enumerated — that would require the
# official API — so the app only shows an explanatory popup for those.
# ---------------------------------------------------------------------------

import json as _json
import re as _re
from urllib.parse import urlparse as _urlparse, quote as _quote
from urllib.request import Request as _Request, urlopen as _urlopen

_UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
       "(KHTML, like Gecko) Chrome/122.0 Safari/537.36")


def spotify_link_type(url):
    """Returns 'track' | 'playlist' | 'album' | '' for a given URL."""
    try:
        parsed = _urlparse(url.strip())
        if "spotify.com" not in (parsed.netloc or ""):
            return ""
        path = parsed.path or ""
        for kind in ("track", "playlist", "album"):
            if _re.search(r"/%s/[A-Za-z0-9]+" % kind, path):
                return kind
        return ""
    except Exception:
        return ""


def _http_get(url, timeout=15):
    req = _Request(url, headers={"User-Agent": _UA, "Accept-Language": "en-US,en;q=0.9"})
    with _urlopen(req, timeout=timeout) as resp:
        return resp.read().decode("utf-8", errors="ignore")


def _spotify_oembed_title(track_url):
    raw = _http_get("https://open.spotify.com/oembed?url=" + _quote(track_url, safe=""))
    data = _json.loads(raw)
    return data.get("title") or "", data.get("thumbnail_url") or ""


def _spotify_artist_from_page(track_url):
    """Best-effort artist extraction from the public track page's meta tags."""
    try:
        html = _http_get(track_url)
    except Exception:
        return ""
    patterns = [
        r'<meta\s+property="og:description"\s+content="([^"]+)"',
        r'<meta\s+name="description"\s+content="([^"]+)"',
        r'<meta\s+name="music:musician_description"\s+content="([^"]+)"',
    ]
    for pattern in patterns:
        m = _re.search(pattern, html, _re.IGNORECASE)
        if not m:
            continue
        desc = m.group(1)
        # Typical shapes: "Song · Artist · Song · 2020" or "Artist · Song · 2020"
        parts = [p.strip() for p in _re.split(r"·|\u00b7", desc) if p.strip()]
        for part in parts:
            low = part.lower()
            if low in ("song", "single", "album", "listen on spotify"):
                continue
            if _re.fullmatch(r"\d{4}", part):
                continue
            return part
    return ""


def _youtube_best_match(query):
    opts = {
        'quiet': True,
        'no_warnings': True,
        'skip_download': True,
        'extract_flat': 'in_playlist',
        'default_search': 'ytsearch',
        'noplaylist': True,
    }
    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info("ytsearch5:" + query, download=False)
    entries = [e for e in (info.get("entries") or []) if e]
    if not entries:
        return None
    # Prefer an official-looking audio result; fall back to the top hit.
    def score(entry):
        title = (entry.get("title") or "").lower()
        channel = (entry.get("channel") or entry.get("uploader") or "").lower()
        s = 0
        if "official audio" in title or "audio" in title:
            s += 3
        if "topic" in channel:
            s += 4
        if "official" in title:
            s += 1
        for bad in ("live", "cover", "remix", "reaction", "karaoke", "sped up", "8d"):
            if bad in title:
                s -= 3
        return s

    best = max(entries, key=score)
    video_id = best.get("id") or ""
    url = best.get("url") or best.get("webpage_url") or ""
    if url and not url.startswith("http"):
        url = "https://www.youtube.com/watch?v=" + url
    if not url and video_id:
        url = "https://www.youtube.com/watch?v=" + video_id

    thumb = ""
    thumbs = best.get("thumbnails") or []
    if thumbs:
        thumb = thumbs[-1].get("url", "")
    if not thumb and video_id:
        thumb = "https://i.ytimg.com/vi/%s/hqdefault.jpg" % video_id

    return {
        "url": url,
        "title": best.get("title") or "Unknown",
        "channel": best.get("channel") or best.get("uploader") or "YouTube",
        "thumbnailUrl": thumb,
        "durationText": _format_duration(best.get("duration", 0)),
    }


def resolve_spotify_track(url):
    """
    Public-data-only Spotify track resolution:
      title (oEmbed) [+ artist (page meta)] -> YouTube search -> best match.
    Returns a dict the UI shows as a confirmation card before downloading.
    """
    title, thumb = _spotify_oembed_title(url)
    if not title:
        raise ValueError("Could not read this Spotify track")

    artist = _spotify_artist_from_page(url)
    # The oEmbed title sometimes already contains the artist; don't duplicate it.
    if artist and artist.lower() in title.lower():
        query = title
    elif artist:
        query = "%s %s" % (title, artist)
    else:
        query = title

    match = _youtube_best_match(query)
    if not match:
        raise ValueError("No YouTube match found for this track")

    match["spotifyTitle"] = title
    match["spotifyArtist"] = artist
    match["spotifyThumbnailUrl"] = thumb
    return match


# ---------------------------------------------------------------------------
# Single-song albums / playlists
#
# Some "albums" are really a single released as an album, and to the user that
# link looks identical to a real album. A logged-out visitor still gets the
# full tracklist embedded in the public page HTML (meta music:song tags plus
# the embedded JSON payload), so we can count tracks without any API.
#
# Everything here is deliberately best-effort: any doubt at all returns None,
# and the caller falls back to the "convert your playlist" popup.
# ---------------------------------------------------------------------------

def _spotify_collection_track_urls(url):
    """Best-effort list of unique track URLs embedded in a public album/playlist page."""
    try:
        html = _http_get(url, timeout=12)
    except Exception:
        return None

    ordered = []
    seen = set()

    def _add(track_id):
        if track_id and track_id not in seen:
            seen.add(track_id)
            ordered.append("https://open.spotify.com/track/" + track_id)

    # 1) <meta name="music:song" content="https://open.spotify.com/track/ID">
    for m in _re.finditer(
        r'<meta[^>]+(?:name|property)="music:song"[^>]+content="[^"]*?/track/([A-Za-z0-9]+)"',
        html, _re.IGNORECASE
    ):
        _add(m.group(1))
    if ordered:
        return ordered

    # 2) Embedded JSON payload: spotify:track:ID / "/track/ID"
    for m in _re.finditer(r'spotify:track:([A-Za-z0-9]{20,})', html):
        _add(m.group(1))
    if ordered:
        return ordered
    for m in _re.finditer(r'open\.spotify\.com/track/([A-Za-z0-9]{20,})', html):
        _add(m.group(1))
    return ordered or None


def _spotify_declared_track_count(url):
    """Reads a declared track count from the page, or None when unavailable."""
    try:
        html = _http_get(url, timeout=12)
    except Exception:
        return None
    m = _re.search(r'"totalTracks"\s*:\s*(\d+)', html)
    if m:
        try:
            return int(m.group(1))
        except Exception:
            pass
    m = _re.search(
        r'<meta[^>]+(?:name|property)="(?:og:)?description"[^>]+content="([^"]+)"',
        html, _re.IGNORECASE
    )
    if m:
        c = _re.search(r'(\d+)\s+songs?\b', m.group(1), _re.IGNORECASE)
        if c:
            try:
                return int(c.group(1))
            except Exception:
                pass
    return None


def spotify_collection_single_track_url(url):
    """
    Returns the single track's URL when an album/playlist reliably contains
    exactly one song, otherwise "" (caller then shows the popup).
    """
    try:
        tracks = _spotify_collection_track_urls(url)
        declared = _spotify_declared_track_count(url)

        # Both signals must agree on "1" whenever both are available.
        if declared is not None and declared != 1:
            return ""
        if tracks is None:
            return ""
        if len(tracks) != 1:
            return ""
        return tracks[0]
    except Exception:
        return ""


def resolve_spotify_collection_single(url):
    """
    If this album/playlist holds exactly one song, resolve it through the same
    track flow used for /track/ links. Returns None when it doesn't apply.
    """
    track_url = spotify_collection_single_track_url(url)
    if not track_url:
        return None
    try:
        return resolve_spotify_track(track_url)
    except Exception:
        return None
